services:
  postgres:
    image: postgres:14
    container_name: customers_postgres
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: